language: java
matrix:
    include:
        - os: linux
          jdk: oraclejdk8
          services:
              - docker
          env: goal=verify
        - os: osx
          osx_image: xcode8.2
          env: goal=test
script:
    - mvn $goal
after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then .travis/publish-documentation.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then .travis/deploy-snapshot; fi
branches:
    only:
        - master
