sudo: required
services:
    - docker
language: java
jdk:
    - oraclejdk8
script: mvn verify
after_success:
    - .travis/publish-documentation.sh
    - .travis/deploy-snapshot
branches:
    only:
        - master
