#!/bin/bash
if [ "$TRAVIS_BRANCH" == "master" ] && [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]
then

    openssl aes-256-cbc -K $encrypted_1aab6c06035c_key -iv $encrypted_1aab6c06035c_iv -in .travis/travis_rsa.enc -out .travis/travis_rsa -d
    chmod og-rwx .travis/travis_rsa

    eval `ssh-agent -s`
    ssh-add .travis/travis_rsa

    git clone git@github.com:FaustXVI/junit5-docker.git out
    cd out

    git branch -a
    git checkout $TRAVIS_BRANCH
    git config --global user.email "travis@travis-ci.org"
    git config --global user.name "travis-ci"

    mvn javadoc:javadoc
    VERSION=$(ls target/site/apidocs)
    rm -r docs/javadoc/$VERSION
    mv target/site/apidocs/$VERSION docs/javadoc/
    git add docs/javadoc

    CHANGED=$(git status -uno -s)
    echo $CHANGED

    if [ -n "$CHANGED" ]
    then
        git commit -m "Add javadoc"
        git push origin $TRAVIS_BRANCH
    else
        echo "No javadoc to commit"
    fi
else
    echo "On a branch, doing nothing !"
fi
